### ISSUE TITLE
能否增加DataGrip  的支持？

### ISSUE THREAD

**Issue by qinyinglun** [zoulejiu/mybatisSmartCodeHelp#11]
能否增加DataGrip  的支持？
目前数据库都在DataGrip 管理 使用 
idea  自带的够用但是有很多局限。

**Comment by zoulejiu** [comment]
DataGrip 的用处不大，这上面都是 执行sql 的，这个插件是要去生成mybatis 文件的，DataGrip 生成文件你还要移到项目中

**Comment by qinyinglun** [comment]
目前插件我看是要选择项目根目录和选择包名路径的
支持datagrip   数据库管理软件里直接选项目根目录和包路径就可以了
数据库链接比较多的时候，每次都用idea自带的database插件是不够用的，
页面太小，功能不够完整

**Comment by zoulejiu** [comment]
这个没办法去支持，这个插件依赖Java，不是一个单纯的生成工具，如果要支持，就必须把依赖特色的自动检测功能移除，这显然是不合理的，抱歉
