### ISSUE TITLE
mybatis-plus多表关联查询，mybatisSmartCodeHelpPro插件爆红

### ISSUE THREAD

**Issue by wangweiping** [zoulejiu/mybatisSmartCodeHelp#14]
使用IntelliJ IDEA Ultimate版本为2021.1.3；mybatisSmartCodeHelpPro插件版本为2022.1.9
![image](https://user-images.githubusercontent.com/18497716/167220346-db1c7ccc-7d2b-4a2e-97e4-c6b977b9b4c5.png)

![image](https://user-images.githubusercontent.com/18497716/167221026-2c525706-a11d-43cd-8cd5-5f23596401ad.png)

程序执行没有问题，打印sql如下：
![1RNV5_55~O`_XN0DY ~VIYO](https://user-images.githubusercontent.com/18497716/167221416-495ddd77-50aa-4600-af7c-29e85bf714eb.png)

**Comment by zoulejiu** [comment]
这是Database Tool 你那边没配置好吧

**Comment by wangweiping** [comment]
嗯嗯，我刚刚仔细看文档重新配置了，就好了，哈哈哈。
这个issues可以关闭，能删除吗？

**Comment by wangweiping** [comment]
已经解决了
