### ISSUE TITLE
能连oracle吗？现在好像只能连mysql

### ISSUE THREAD

**Issue by wePeople** [zoulejiu/mybatisSmartCodeHelp#2]
RT。感谢

**Comment by zoulejiu** [comment]
是的现在只能连接Mysql ，后期会加上的，个人开发没那么充足的时间,速度没那么快见谅

**Comment by zoulejiu** [comment]
> RT。感谢

你Oracle 是多少版本的？

**Comment by wePeople** [comment]
> > RT。感谢
> 
> 你Oracle 是多少版本的？

Oracle Database 11g Enterprise Edition Release 11.2.0.1.0 - 64bit Production

**Comment by zoulejiu** [comment]
> > > RT。感谢
> > 
> > 
> > 你Oracle 是多少版本的？
> 
> Oracle Database 11g Enterprise Edition Release 11.2.0.1.0 - 64bit Production
你能加下群吗，我这边正在在做这个，我本地没有oracle 想邀请你一起测试下777347929

**Comment by zoulejiu** [comment]
1.1.4版本已支持
