### ISSUE TITLE
4K屏幕下，放大175%，图标不清晰

### ISSUE THREAD

**Issue by slankka** [zoulejiu/mybatisSmartCodeHelp#3]
希望更换更高清的icon资源。

![Icon](https://user-images.githubusercontent.com/8142133/126733337-4d3c7850-69b0-4d45-8796-22c42ce90088.png)

**Comment by zoulejiu** [comment]
安排~

**Comment by wangweiping** [comment]
可以使用svg矢量图标吗？

**Comment by zoulejiu** [comment]
> 可以使用svg矢量图标吗？

已经在使用svg 替换中了，下个版本会放出

**Comment by zoulejiu** [comment]
1.1.8 版本已更新图标
