### ISSUE TITLE
Inspection 自动拆装箱不支持

### ISSUE THREAD

**Issue by slankka** [zoulejiu/mybatisSmartCodeHelp#4]
Integer和int 肯定能互转呀，没必要Inspect提示

![image](https://user-images.githubusercontent.com/8142133/126733395-4b1972ef-56aa-4f20-9b35-0cbecbd6d650.png)

**Comment by zoulejiu** [comment]
安排~

**Comment by zoulejiu** [comment]
1.1.8 版本已修复
