### ISSUE TITLE
Mapper接口多个XML关联不显示Gutter Icon

### ISSUE THREAD

**Issue by slankka** [zoulejiu/mybatisSmartCodeHelp#5]
如图
![image](https://user-images.githubusercontent.com/8142133/126733914-9e0bed4d-648f-4978-b0f6-9f7c6f2d4c57.png)

版本
IntelliJ IDEA Community 2021.1.3

**Comment by zoulejiu** [comment]
没太明白你的问题，是左边的图片不显示吗？

**Comment by slankka** [comment]
对，左边的Gutter Icon不显示。
P.S. 葛俊的插件支持。

**Comment by zoulejiu** [comment]
你这是方法导航到xml 中的操作吧，搜到了多个xml ，出现下拉框，让你选择，下拉框对应的左边是没有图标的

**Comment by slankka** [comment]
下拉框是示意多个xml，对下拉框没有需求。

是说**左边的小图标**不显示，能显示就完美了。

**Comment by zoulejiu** [comment]
这是一个pop ，和底部文件的左侧栏是没有关联的，所以无法实现这个效果....
