### ISSUE TITLE
mybatis的.xml文件嵌套查询报红

### ISSUE THREAD

**Issue by wangweiping** [zoulejiu/mybatisSmartCodeHelp#7]
![image](https://user-images.githubusercontent.com/18497716/126818991-916b0b5f-e910-4668-8b68-4ed12e9b60c0.png)

在idea2020.3.4版本中，mybatis的.xml文件嵌套查询报红

**Comment by zoulejiu** [comment]
collection 这个节点现在还没适配，下个版本适配下

**Comment by zoulejiu** [comment]
1.1.8版本已修复
